### PR TITLE
Fix calling yq to parse output

### PR DESCRIPTION
**Pull request by brablc**
Dispatching workflows does not work. This fixes it.

### CODE REVIEW

**Review by topaxi — APPROVED** [review]

**Comment by topaxi** [comment]
thank you! :)

**Comment by topaxi** [comment]
This breaks on my machine, my `yq` command does not have an `-o` option :thinking:

**Comment by brablc** [comment]
Oh, Ubuntu has 3.1 in apt. I will fix it!

**Comment by topaxi** [comment]
Great! Thank you! I reverted the commit until then. Not sure how to easily feature detect this, maybe we just add a note in the README that `yq` is required in a specific version (range?).

Mine is 3.4.3, which seems to be the latest version.

Although I do think supporting an older version that is used in a popular distro like Ubuntu would be good.

**Pull request merged**
